---
title: "git_01"
author: "Maria Cabanillas"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

There was an ancient City, stricken down  
With a strange frenzy, and for many a day  
They paced from morn to eve the crowded town,  
And danced the night away.  
I asked the cause: the aged man grew sad:  
  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

How lush, how loose, the uninhibited squash   
If ever hearts (and these immoderate leaves  
Are vegetable hearts) were worn on sleeves,  
The squash’s are. In green the squash vine gushes.  
The flowers are cornucopias of summer,  
Briefly exuberant and cheaply golden.  
  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
Shining with all his might:  
  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

the slime of all my yesterdays  
rots in the hollow of my skull  
and if my stomach would contract  
because of some explicable phenomenon  
such as pregnancy or constipation  
I would not remember you  
or that because of sleep  
infrequent as a moon of greencheese  
that because of food  
nourishing as violet leaves  
that because of these  
and in a few fatal yards of grass  
in a few spaces of sky and treetops  
a future was lost yesterday  
as easily and irretrievably  
as a tennis ball at twilight  
  
